### ISSUE TITLE
Polybar shadow

### ISSUE THREAD

**Issue by felipendc** [ngynLk/polybar-themes#3]
Could you tell me how did you add shadow to these Polybars , please?
They look so beautiful!

https://raw.githubusercontent.com/ngynLk/polybar-themes/master/san/scrot1.png
https://raw.githubusercontent.com/ngynLk/polybar-themes/master/cherryblocks/scrot.png
https://raw.githubusercontent.com/ngynLk/polybar-themes/master/blocks/scrot-square.png
https://raw.githubusercontent.com/ngynLk/polybar-themes/master/blocks/scrot2.png
https://raw.githubusercontent.com/ngynLk/polybar-themes/master/blocks/scrot-rounded.png
https://raw.githubusercontent.com/ngynLk/polybar-themes/master/miniblocks/scrot.png
https://raw.githubusercontent.com/ngynLk/polybar-themes/master/miniblocks/scrot.png
https://raw.githubusercontent.com/ngynLk/polybar-themes/master/classic2/scrot.png

I'm running: Arcolinuxb  
Compositor: picom 
Thx.

**Comment by kiddae** [comment]
Hello, I'm sorry for the late answer. 
In `picom`, you can add `wintypes` rules for docks. There, set the `full-shadow` option to `true`.
That way, the shadows look natural.

```
wintypes:
{
	dock = { shadow = true; full-shadow = true}
} 
```
I'm glad you like my themes!
