### ISSUE TITLE
Some icons and scripts doesn't work in "Block" theme

### ISSUE THREAD

**Issue by EliasLeguizamon123** [ngynLk/polybar-themes#5]
Hi,
I in love whit its theme "Block", but for some reason i can't get the icons and poweroff script to work 
![errorPolybar](https://user-images.githubusercontent.com/25516473/99069266-c96dd680-258c-11eb-89b8-11c70f2ef2b4.png)
attached image to show how it currently looks

**Comment by kiddae** [comment]
Have you installed all the fonts required?
For my `powermenu` script it uses another script called `prompt` and all of that needs `rofi` installed.

**Comment by EliasLeguizamon123** [comment]
Hi!, yes i do, i attached my log of the required fonts (im not sure if i have installed FontAwesome correctly)
```
λ /home/ fc-list | grep -E "SFMono|IPA|FontAwesome"
/home/mole/.local/share/fonts/SFMonoBold.otf: SF Mono:style=Bold
/home/mole/.local/share/fonts/SFMonoHeavyItalic.otf: SF Mono:style=Heavy Italic
/home/mole/.local/share/fonts/SFMonoBoldItalic.otf: SF Mono:style=Bold Italic
/home/mole/.local/share/fonts/SFMonoSemibold.otf: SF Mono:style=Semibold
/home/mole/.local/share/fonts/SFMonoMedium.otf: SF Mono:style=Medium
/usr/share/fonts/opentype/font-awesome/FontAwesome.otf: FontAwesome:style=Regular
/home/mole/.local/share/fonts/SFMonoHeavy.otf: SF Mono:style=Heavy
/home/mole/.local/share/fonts/SFMonoLight.otf: SF Mono:style=Light
/home/mole/.local/share/fonts/SFMonoMediumItalic.otf: SF Mono:style=Medium Italic
/home/mole/.local/share/fonts/SFMonoRegular.otf: SF Mono:style=Regular
/home/mole/.local/share/fonts/SFMonoSemiboldItalic.otf: SF Mono:style=Semibold Italic
/home/mole/.local/share/fonts/IPAGothic_24302.ttf: IPAGothic,IPAゴシック:style=Regular
/home/mole/.local/share/fonts/SFMonoRegularItalic.otf: SF Mono:style=Regular Italic
/home/mole/.local/share/fonts/SFMonoLightItalic.otf: SF Mono:style=Light Italic
/usr/share/fonts/truetype/font-awesome/fontawesome-webfont.ttf: FontAwesome:style=Regular
λ /home/ 
```
Also add prompt script in my `.config/polybar/scripts` directory and nothing change.

**Comment by kiddae** [comment]
Hello!
Try to change the font name for FontAwesome in the config to match what's in your output of `fc-list`. I don't remember how I installed FontAwesome personally so I can't really tell you. Normally SF Mono should show on your bar, but i don't know why it's not showing.
For the script, put it somewhere that is included in your `$PATH`. You have to get the `powermenu` script too (it's not really an impressive script make your own if you prefer).

**Comment by EliasLeguizamon123** [comment]
Hi friend!.
I add `powermenu` and `prompt` in my `$PATH` but doesn't work, maybe because the fonts doesn't work
`λ ~/ echo $PATH
/home/mole/mole/.config/polybar/scripts/prompt:/home/mole/mole/.config/polybar/scripts/powermenu:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games`

now i try to fix AwesomeFont, or install if not installed, fc-list log:

` λ ~/ fc-list | grep "FontAwesome"
/usr/share/fonts/opentype/font-awesome/FontAwesome.otf: FontAwesome:style=Regular
/usr/share/fonts/truetype/font-awesome/fontawesome-webfont.ttf: FontAwesome:style=Regular`

**Comment by kiddae** [comment]
For the scripts, put them in a folder (I recommend having a folder dedicated to all of your scripts — something like `~/.scripts` or `~/bin`) and then add that folder to your $PATH. If you put the executables directly in the PATH variable it won't work.
To get FontAwesome to work replace the entry from the config file with the correct name (here it's `FontAwesome`).
Good luck! You seem to be a beginner.

**Comment by kiddae** [comment]
Oops wrong manipulation

**Comment by EliasLeguizamon123** [comment]
Thanks Friend, you guessed it! i started using linux about 2 weeks ago, renaming to FontAwesome worked perfectly
![fixPolybar](https://user-images.githubusercontent.com/25516473/99198203-c41fb000-2775-11eb-9bb8-f0548ad09c57.png)
