### ISSUE TITLE
leafy walls

### ISSUE THREAD

**Issue by krithravi** [ngynLk/polybar-themes#9]
Hi! Would you still have the link to the wallpaper you use for "san", "classic" and "classic2" (the leafy one)?
Thank you!!

**Comment by kiddae** [comment]
Hi, I believe you're talking about [this](https://raw.githubusercontent.com/kiddae/wallpapers/master/nature/8xpvv2.jpg) wallpaper?
I'm sorry for the very late answer.

**Comment by krithravi** [comment]
Yes, thank you so much! :leaves:
